# Core system services for my projects
version: '3.7'

services:
  bind:
    image: sameersbn/bind:latest
    environment:
      ROOT_PASSWORD: xxx
    volumes:
      - bind_data_nfs:/data:rw
    ports:
        - 53:53/tcp
        - 53:53/udp
        - 10000:10000/tcp
    deploy:
      placement:
        constraints:
          - node.platform.os == linux
  smtp:
    image: rylorin/postfix-relay:latest
    environment:
      POSTFIX_virtual_alias_domains: villamilawines.com 123-group.com
    configs:
      - source: virtual
        target: /etc/postfix/conf.d/virtual
    ports:
      - 25:25/tcp
    deploy:
      placement:
        constraints:
          - node.platform.os == linux
  websites:
    image: caddy:2.0.0-alpine
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - core_sslcerts:/data/:rw
      - web:/usr/share/caddy/:ro
    networks:
      # default network not used
      - dmz_network
      # portainer_agent_network is necessary for reverse proxying to portainer web interface
      - portainer_agent_network
    configs:
      - source: Caddyfile
        target: /etc/caddy/Caddyfile
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
      
networks:
  dmz_network:
    driver: overlay
    attachable: true
  portainer_agent_network:
    external: true

configs:
  Caddyfile:
    external: true
  virtual:
    external: true

volumes:
  web:
  core_sslcerts:
    external: true
  bind_data_nfs:
    external: true
